# Generated by Django 3.1.2 on 2020-10-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0005_auto_20201029_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
