# Generated by Django 3.1.2 on 2020-10-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0006_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
