# Generated by Django 3.1.2 on 2020-10-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201030_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bid',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchers', to='auctions.Listing'),
        ),
    ]
