# Generated by Django 3.1.2 on 2020-10-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0011_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
