# Generated by Django 3.1.2 on 2020-11-02 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201102_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categorie',
        ),
        migrations.AddField(
            model_name='listing',
            name='categorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.categorie'),
        ),
    ]
