# Generated by Django 3.1.2 on 2020-11-02 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0016_auto_20201102_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categorie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings',
                                    to='auctions.categorie'),
        ),
    ]
