# Generated by Django 3.1.2 on 2020-11-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20201102_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='categorie',
            new_name='category',
        ),
    ]
